"""Simplify RepresentativeWork model

Revision ID: 06a054480286
Revises: 4e587f62f36a
Create Date: 2025-08-26 16:27:25.072308

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06a054480286'
down_revision: Union[str, Sequence[str], None] = '4e587f62f36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representativework',
                  sa.Column('journal', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('representativework',
                  sa.Column('pages', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('representativework',
                  sa.Column('year', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.drop_column('representativework', 'citation')
    op.drop_column('representativework', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representativework',
                  sa.Column('description', sa.VARCHAR(), autoincrement=False,
                            nullable=False))
    op.add_column('representativework',
                  sa.Column('citation', sa.VARCHAR(), autoincrement=False,
                            nullable=False))
    op.drop_column('representativework', 'year')
    op.drop_column('representativework', 'pages')
    op.drop_column('representativework', 'journal')
    # ### end Alembic commands ###
