"""Add in revision column

Revision ID: 49a28bde9987
Revises: 06a054480286
Create Date: 2025-08-26 17:23:01.826980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49a28bde9987'
down_revision: Union[str, Sequence[str], None] = '06a054480286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representativework', sa.Column('is_in_revision', sa.Boolean(), nullable=False))
    op.alter_column('representativework', 'pages',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('representativework', 'year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('representativework', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('representativework', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('representativework', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('representativework', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('representativework', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('representativework', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('representativework', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('representativework', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('representativework', 'year',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('representativework', 'pages',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('representativework', 'is_in_revision')
    # ### end Alembic commands ###
