"""Add volume column in representative work table

Revision ID: 4b8de36ce482
Revises: 49a28bde9987
Create Date: 2025-08-26 21:30:34.676340

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b8de36ce482'
down_revision: Union[str, Sequence[str], None] = '49a28bde9987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representativework',
                  sa.Column('volume', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('representativework', 'volume')
    # ### end Alembic commands ###
