"""Add RepresentativeWork and GalleryImage models

Revision ID: 4e587f62f36a
Revises: d17d7bb52458
Create Date: 2025-08-25 18:13:22.445525

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e587f62f36a'
down_revision: Union[str, Sequence[str], None] = 'd17d7bb52458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cvcontent')
    op.add_column('galleryimage',
                  sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('galleryimage',
                  sa.Column('category', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.drop_column('galleryimage', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galleryimage',
                  sa.Column('image_url', sa.VARCHAR(), autoincrement=False,
                            nullable=False))
    op.drop_column('galleryimage', 'category')
    op.drop_column('galleryimage', 'image_path')
    op.create_table('cvcontent',
                    sa.Column('id', sa.INTEGER(), autoincrement=True,
                              nullable=False),
                    sa.Column('content', sa.VARCHAR(), autoincrement=False,
                              nullable=False),
                    sa.Column('section', sa.VARCHAR(), autoincrement=False,
                              nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False,
                              nullable=False),
                    sa.Column('order_index', sa.INTEGER(), autoincrement=False,
                              nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('cvcontent_pkey'))
                    )
    # ### end Alembic commands ###
