"""Add CV model for new cv method

Revision ID: 61460bd6bea6
Revises: 7b2d2561ae87
Create Date: 2025-08-31 16:17:47.221953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61460bd6bea6'
down_revision: Union[str, Sequence[str], None] = '7b2d2561ae87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
