"""Add Research_Highlights and Cover Arts

Revision ID: a6945d73bf13
Revises: 61460bd6bea6
Create Date: 2025-09-09 00:19:15.280792

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6945d73bf13'
down_revision: Union[str, Sequence[str], None] = '61460bd6bea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researchhighlight',
                  sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=True))
    op.add_column('researchhighlight',
                  sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=True))
    op.add_column('researchhighlight',
                  sa.Column('order_index', sa.Integer(), nullable=False))
    op.add_column('researchhighlight',
                  sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('researchhighlight',
                  sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('researchhighlight',
                  sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researchhighlight', 'updated_at')
    op.drop_column('researchhighlight', 'created_at')
    op.drop_column('researchhighlight', 'is_active')
    op.drop_column('researchhighlight', 'order_index')
    op.drop_column('researchhighlight', 'alt_text')
    op.drop_column('researchhighlight', 'description')
    # ### end Alembic commands ###
