"""Update publication model with detailed data

Revision ID: d17d7bb52458
Revises: d223266b7375
Create Date: 2025-08-17 22:03:34.707245

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd17d7bb52458'
down_revision: Union[str, Sequence[str], None] = 'd223266b7375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication',
                  sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('publication',
                  sa.Column('month', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=True))
    op.add_column('publication',
                  sa.Column('arxiv', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=True))
    op.add_column('publication',
                  sa.Column('is_corresponding_author', sa.Boolean(),
                            nullable=False))
    op.add_column('publication',
                  sa.Column('is_equal_contribution', sa.Boolean(),
                            nullable=False))
    op.add_column('publication', sa.Column('contribution_type',
                                           sqlmodel.sql.sqltypes.AutoString(),
                                           nullable=False))
    op.add_column('publication',
                  sa.Column('status', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('publication',
                  sa.Column('featured_info', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=True))
    op.add_column('publication',
                  sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'updated_at')
    op.drop_column('publication', 'featured_info')
    op.drop_column('publication', 'status')
    op.drop_column('publication', 'contribution_type')
    op.drop_column('publication', 'is_equal_contribution')
    op.drop_column('publication', 'is_corresponding_author')
    op.drop_column('publication', 'arxiv')
    op.drop_column('publication', 'month')
    op.drop_column('publication', 'number')
    # ### end Alembic commands ###
