"""Add CV models and data

Revision ID: d223266b7375
Revises: e79bc59087f0
Create Date: 2025-08-17 21:55:34.056854

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd223266b7375'
down_revision: Union[str, Sequence[str], None] = 'e79bc59087f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('organization',
                              sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('rank', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('conference',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('conference_name',
                              sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('presentation_type',
                              sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('award', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('education',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('start_year', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('end_year', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('advisor', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('experience',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('organization',
                              sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('start_year', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('end_year', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('host_advisor',
                              sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('galleryimage',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('order_index', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('cvcontent',
                  sa.Column('section', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('cvcontent',
                  sa.Column('title', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('cvcontent',
                  sa.Column('order_index', sa.Integer(), nullable=False))
    op.add_column('cvcontent',
                  sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('cvcontent', 'content',
                    existing_type=sa.TEXT(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    nullable=False)
    op.add_column('media',
                  sa.Column('source', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('media', sa.Column('date', sqlmodel.sql.sqltypes.AutoString(),
                                     nullable=False))
    op.add_column('media',
                  sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=True))
    op.add_column('media',
                  sa.Column('category', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('media',
                  sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('media', 'url',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_column('media', 'publication_date')
    op.drop_column('media', 'outlet')
    op.add_column('publication',
                  sa.Column('year', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False))
    op.add_column('publication',
                  sa.Column('impact_factor', sa.Float(), nullable=True))
    op.add_column('publication',
                  sa.Column('is_first_author', sa.Boolean(), nullable=False))
    op.add_column('publication',
                  sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_publication_title'), table_name='publication')
    op.drop_column('publication', 'publication_date')
    op.drop_column('publication', 'contribution')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication',
                  sa.Column('contribution', sa.VARCHAR(), autoincrement=False,
                            nullable=False))
    op.add_column('publication',
                  sa.Column('publication_date', sa.DATE(), autoincrement=False,
                            nullable=False))
    op.create_index(op.f('ix_publication_title'), 'publication', ['title'],
                    unique=False)
    op.drop_column('publication', 'created_at')
    op.drop_column('publication', 'is_first_author')
    op.drop_column('publication', 'impact_factor')
    op.drop_column('publication', 'year')
    op.add_column('media',
                  sa.Column('outlet', sa.VARCHAR(), autoincrement=False,
                            nullable=False))
    op.add_column('media',
                  sa.Column('publication_date', sa.DATE(), autoincrement=False,
                            nullable=False))
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.alter_column('media', 'url',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('media', 'created_at')
    op.drop_column('media', 'category')
    op.drop_column('media', 'description')
    op.drop_column('media', 'date')
    op.drop_column('media', 'source')
    op.alter_column('cvcontent', 'content',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(),
                    type_=sa.TEXT(),
                    nullable=True)
    op.drop_column('cvcontent', 'created_at')
    op.drop_column('cvcontent', 'order_index')
    op.drop_column('cvcontent', 'title')
    op.drop_column('cvcontent', 'section')
    op.drop_table('galleryimage')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('conference')
    op.drop_table('award')
    # ### end Alembic commands ###
