"""Initial migration

Revision ID: e79bc59087f0
Revises: 
Create Date: 2025-08-17 03:56:57.531042

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e79bc59087f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvcontent',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('media',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('outlet', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('publication_date', sa.Date(), nullable=False),
                    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.create_table('publication',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('journal', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('publication_date', sa.Date(), nullable=False),
                    sa.Column('contribution',
                              sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('volume', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('pages', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_publication_title'), 'publication', ['title'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_title'), table_name='publication')
    op.drop_table('publication')
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_table('media')
    op.drop_table('cvcontent')
    # ### end Alembic commands ###
